# deployments/cloudbuild.yaml

steps:
# Step 1: Build the backend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mammoscan-backend:latest'
    - '-f'
    - 'backend/Dockerfile.api'
    - '.'

# Step 2: Build the frontend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mammoscan-frontend:latest'
    - '-f'
    - 'web/Dockerfile.web'
    - '.'

# After the steps are complete, Cloud Build will automatically push
# these two images to your project's Google Container Registry (GCR).
images:
  - 'gcr.io/$PROJECT_ID/mammoscan-backend:latest'
  - 'gcr.io/$PROJECT_ID/mammoscan-frontend:latest'