# deployments/cloudbuild.yaml

steps:
# Step 1: Build the backend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mammoscan-backend:latest'
    - '-f'
    - 'backend/Dockerfile.api'
    - '.'  # Root context (needs access to models/ and backend/)

# Step 2: Build the frontend Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mammoscan-frontend:latest'
    - '-f'
    - 'web/Dockerfile.web'
    - './web'  # Changed from '.' to './web'

images:
  - 'gcr.io/$PROJECT_ID/mammoscan-backend:latest'
  - 'gcr.io/$PROJECT_ID/mammoscan-frontend:latest'