# deployments/cloudbuild.yaml
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mammoscan-repo/mammoscan-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
    
  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mammoscan-repo/mammoscan-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mammoscan-repo/mammoscan-backend:latest'
    
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mammoscan-repo/mammoscan-frontend:latest'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mammoscan-repo/mammoscan-backend:latest'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mammoscan-repo/mammoscan-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY