# .github/workflows/cd.yml

name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: mammoscan-ai
  GCP_REGION: europe-west1
  BACKEND_SERVICE_NAME: mammoscan-backend
  FRONTEND_SERVICE_NAME: mammoscan-frontend

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/15175657305/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@mammoscan-ai.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and Push Docker images
        run: |-
          set +e
          gcloud builds submit --config=deployments/cloudbuild.yaml .
          BUILD_EXIT_CODE=$?
          
          gcloud container images describe gcr.io/${{ env.GCP_PROJECT_ID }}/mammoscan-backend:latest
          gcloud container images describe gcr.io/${{ env.GCP_PROJECT_ID }}/mammoscan-frontend:latest
          
          if [ $? -eq 0 ]; then
            echo "Images built and pushed successfully"
            exit 0
          else
            exit $BUILD_EXIT_CODE
          fi
      
      - name: Deploy Backend to Cloud Run
        run: |-
          gcloud run deploy ${{ env.BACKEND_SERVICE_NAME }} \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/mammoscan-backend:latest \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --set-env-vars=MODEL_GCS_BUCKET=mammoscan-ai-models,MODEL_GCS_OBJECT=champion_model.onnx

      - name: Deploy Frontend to Cloud Run
        run: |-
          BACKEND_URL=$(gcloud run services describe ${{ env.BACKEND_SERVICE_NAME }} --platform managed --region ${{ env.GCP_REGION }} --format 'value(status.url)')
          
          gcloud run deploy ${{ env.FRONTEND_SERVICE_NAME }} \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/mammoscan-frontend:latest \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=API_URL=${BACKEND_URL}/api/v1/predict